"""Initial migration.

Revision ID: bd0f5c1024db
Revises: 
Create Date: 2021-03-14 11:55:10.658934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0f5c1024db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('permission_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('userencryption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=True),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('nonce', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpermissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_email_encrypted', sa.Integer(), nullable=True),
    sa.Column('user_password_encrypted', sa.Integer(), nullable=True),
    sa.Column('user_first_name_encrypted', sa.Integer(), nullable=True),
    sa.Column('user_middle_name_encrypted', sa.Integer(), nullable=True),
    sa.Column('user_last_name_encrypted', sa.Integer(), nullable=True),
    sa.Column('activation_code', sa.String(length=255), nullable=True),
    sa.Column('activitaion_status', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_email_encrypted'], ['userencryption.id'], ),
    sa.ForeignKeyConstraint(['user_first_name_encrypted'], ['userencryption.id'], ),
    sa.ForeignKeyConstraint(['user_last_name_encrypted'], ['userencryption.id'], ),
    sa.ForeignKeyConstraint(['user_middle_name_encrypted'], ['userencryption.id'], ),
    sa.ForeignKeyConstraint(['user_password_encrypted'], ['userencryption.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_code'),
    sa.UniqueConstraint('modified_by'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('userpermissions')
    op.drop_table('userencryption')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
